# Generated by Django 3.2.25 on 2025-08-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_auto_20250727_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('confirmé', 'Confirmé'), ('payé', 'Payé'), ('en_attente', 'En attente'), ('annulé', 'Annulé')], default='en_attente', max_length=50),
        ),
    ]
