# Generated by Django 5.2.5 on 2025-08-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_alter_facture_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='paymentStatus',
            field=models.CharField(choices=[('payé', 'Payé'), ('en_attente', 'En attente'), ('partiel', 'Partiel'), ('en_cours', 'En cours'), ('remboursé', 'Remboursé'), ('annule', 'Annulé')], default='en_attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='facture',
            name='dateReturn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='dateTravel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('confirmé', 'Confirmé'), ('payé', 'Payé'), ('en_attente', 'En attente'), ('annulé', 'Annulé'), ('en_cours', 'En cours'), ('annule', 'Annulé')], default='en_attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='facture',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
