# Generated by Django 5.2.5 on 2025-09-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activite',
            old_name='priceChild',
            new_name='priceGuide',
        ),
    ]
